@startuml

start

: Create a Structure;
: Display Menu;
: Get input choice;

while (while the choice is not exit) is (yes)

: Switch choice;
fork
-> case 1;
: Insertion;

fork again
-> case 2;
: Deletion;

fork again
-> case 3;
: Display;

end fork

: Get input choice;

endwhile (no)

stop

@enduml










/'
!pragma useVerticalIf on
: Create a Structure;
: Create a funtion for insert, delete and display;

repeat

if (if user selected insertion) then (yes)
: Execute all the steps inside insertion funtion;

else if (if user selected deletion) then (yes)
: Execute all the steps inside deletion function;

else (No)
: Display all the elements from the list;

endif

repeat while (User not exiting loop) is (yes)
-> 

/'
if (if user selected insertion) then (yes)
: Execute all the steps inside insertion funtion;

else if (if user selected deletion) then (yes)
: Execute all the steps inside deletion function;

else (No)
: Display all the elements from the list;

repeat while (User not exiting loop) is (yes)















































/': Create a Structure;
: Create a Menu and get an Input(choice) from user;
: Based on the selected choice, Perform addition or Deletion or Display List;'/


/': Create a Structure and name it as person
             for example "struct person";
: Declare the functions which are needed to be done
       i.e, void add(); void delete(); void display();;

repeat

: Now inside main function, create the Menu with contents like
                    "add entry, delete entry and display";
: Print that Menu and get a choice from user;
: Using switch cases, perform the action choosed by user;

/': After user selecting their choice, slide inside and display 
            them additional choices using switch cases;'/




/': Print all the menu available so that user
    can choose their required operation;

: Now use switch cases to access inside 
       each and every choices available;'/

/'repeatwhile ()

: Now use the functions "add(), delete(), display()" which we declared earlier
                 and perform the neccessary choices given in the Menu;
: Display the list whenever user make a choice 'display';

stop

@enduml

